domainName: dev-grafana.aks.com

nodeExporter:
   enabled: true

# ENABLE Kubelet for container metrics
kubelet:
  enabled: true
  
#grafana:
#  service:
#    type: NodePort

# DISABLE EKS-Managed Control Plane scraping (these don't exist on user nodes)
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false
kubeProxy:
  enabled: false

# Standard memory/CPU requests to keep Prometheus stable
prometheus:
  prometheusSpec:
    # --- ALLOW DISCOVERY ACROSS ALL NAMESPACES & LABELS ---
    # Disables the default Helm chart behavior that automatically injects a release: helm-release-name label requirement into Prometheus's label selector when serviceMonitorSelector is empty.
    serviceMonitorSelectorNilUsesHelmValues: false
    # # Sets the target label filter to match all labels (empty selector), allowing Prometheus to scrape any ServiceMonitor regardless of what labels are attached to it.
    serviceMonitorSelector:
      matchLabels: {}
    # Removes namespace restrictions (empty namespace selector), instructing the Prometheus Operator to watch for and discover ServiceMonitor resources across every namespace in your Kubernetes cluster, rather than only in the monitoring namespace.
    serviceMonitorNamespaceSelector:
      matchNames: []
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi
    # Strorage spec
    storageSpec:
          volumeClaimTemplate:
            spec:
              # Use gp3 (provisioned dynamically by the AWS EBS CSI Driver)
              storageClassName: gp3
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
