environment: "staging"
esoRoleArn: "arn:aws:iam::043272859093:role/staging-external-secrets-irsa"

mongodb:
  metrics:
    serviceMonitor:
      labels:
        release: "staging-platform-prometheus-stack"
