environment: "dev"
esoRoleArn: "arn:aws:iam::043272859093:role/dev-external-secrets-irsa"


mongodb:
  metrics:
    serviceMonitor:
      additionalLabels:
        release: "dev-platform-prometheus-stack"
