# mongo-app-gitops-repo/
# └── platform/
#     └── mongodb/
#         ├── secret-store.yaml      # Namespaced SecretStore (Wave 1)
#         ├── external-secret.yaml   # ExternalSecret for SSM (Wave 2)
#         └── values.yaml            # Custom values for Bitnami Helm Chart
# The actual secure cloud service outside of Kubernetes (like AWS SSM Parameter Store or AWS Secrets Manager).
# [ AWS SSM Parameter Store ]  <--- (External Store: Real password lives in AWS)
#            │
#            ▼ (Connected via SecretStore authentication)
# [ External Secrets Operator ]
#            │
#            ▼ (Follows instructions in ExternalSecret YAML)
# [ Native K8s Secret ]         <--- (The Secret: Local K8s secret generated)
#            │
#            ▼
# [ Bitnami MongoDB / App Pod ] <--- (Reads local K8s secret)
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-parameterstore
  namespace: mongodb-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: eso-parameter-store-sa # <--- Tells ESO to present THIS token to AWS
            namespace: mongodb-system