apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-parameter-store-sa
  namespace: mongodb-system
  annotations:
    argocd.argoproj.io/sync-wave: "0" 
    # The pipeline will find this exact string and swap it out
    eks.amazonaws.com/role-arn: {{ .Values.esoRoleArn }}